In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('soil-final.csv')

In [5]:
dataset

DATE-TIME  HP Temp (0-5cm)   Temp 1cm   Temp 2.5cm   Temp 5cm   \
0       1/6/2018 0:00               5.1       6.98         7.45       8.19   
1       1/6/2018 0:20               4.7       6.69         7.18       7.96   
2       1/6/2018 0:40               4.4       6.43         6.95       7.74   
3       1/6/2018 1:00               4.0       6.10         6.61       7.47   
4       1/6/2018 1:20               3.9       6.01         6.51       7.39   
...               ...               ...        ...          ...        ...   
6619  31/8/2018 22:20               9.9      10.81        11.04      11.38   
6620  31/8/2018 22:40               9.5      10.38        10.68      11.06   
6621  31/8/2018 23:00               9.2      10.21        10.52      10.92   
6622  31/8/2018 23:20               9.1      10.07        10.36      10.76   
6623  31/8/2018 23:40               9.1       9.90        10.20      10.60   

      SM (0-5cm)  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0          16.92         NaN         NaN         NaN         NaN          NaN   
1          16.82         NaN         NaN         NaN         NaN          NaN   
2          16.49         NaN         NaN         NaN         NaN          NaN   
3          16.75         NaN         NaN         NaN         NaN          NaN   
4          16.76         NaN         NaN         NaN         NaN          NaN   
...          ...         ...         ...         ...         ...          ...   
6619        9.44         NaN         NaN         NaN         NaN          NaN   
6620        9.44         NaN         NaN         NaN         NaN          NaN   
6621        9.44         NaN         NaN         NaN         NaN          NaN   
6622        9.19         NaN         NaN         NaN         NaN          NaN   
6623        9.19         NaN         NaN         NaN         NaN          NaN   

      Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0             NaN          NaN          NaN          NaN  
1             NaN          NaN          NaN          NaN  
2             NaN          NaN          NaN          NaN  
3             NaN          NaN          NaN          NaN  
4             NaN          NaN          NaN          NaN  
...           ...          ...          ...          ...  
6619          NaN          NaN          NaN          NaN  
6620          NaN          NaN          NaN          NaN  
6621          NaN          NaN          NaN          NaN  
6622          NaN          NaN          NaN          NaN  
6623          NaN          NaN          NaN          NaN  

[6624 rows x 15 columns]

In [7]:
dataset.drop(labels = ['DATE-TIME','Unnamed: 6','Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10','Unnamed: 11','Unnamed: 12','Unnamed: 13','Unnamed: 14'],axis = 1,inplace = True)

In [8]:
dataset

HP Temp (0-5cm)   Temp 1cm   Temp 2.5cm   Temp 5cm   SM (0-5cm)
0                  5.1       6.98         7.45       8.19       16.92
1                  4.7       6.69         7.18       7.96       16.82
2                  4.4       6.43         6.95       7.74       16.49
3                  4.0       6.10         6.61       7.47       16.75
4                  3.9       6.01         6.51       7.39       16.76
...                ...        ...          ...        ...         ...
6619               9.9      10.81        11.04      11.38        9.44
6620               9.5      10.38        10.68      11.06        9.44
6621               9.2      10.21        10.52      10.92        9.44
6622               9.1      10.07        10.36      10.76        9.19
6623               9.1       9.90        10.20      10.60        9.19

[6624 rows x 5 columns]

In [9]:
dataset.info

<bound method DataFrame.info of       HP Temp (0-5cm)   Temp 1cm   Temp 2.5cm   Temp 5cm   SM (0-5cm)
0                  5.1       6.98         7.45       8.19       16.92
1                  4.7       6.69         7.18       7.96       16.82
2                  4.4       6.43         6.95       7.74       16.49
3                  4.0       6.10         6.61       7.47       16.75
4                  3.9       6.01         6.51       7.39       16.76
...                ...        ...          ...        ...         ...
6619               9.9      10.81        11.04      11.38        9.44
6620               9.5      10.38        10.68      11.06        9.44
6621               9.2      10.21        10.52      10.92        9.44
6622               9.1      10.07        10.36      10.76        9.19
6623               9.1       9.90        10.20      10.60        9.19

[6624 rows x 5 columns]>

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6624 entries, 0 to 6623
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   HP Temp (0-5cm)   6624 non-null   float64
 1   Temp 1cm          6624 non-null   float64
 2   Temp 2.5cm        6624 non-null   float64
 3   Temp 5cm          6624 non-null   float64
 4   SM (0-5cm)        6624 non-null   float64
dtypes: float64(5)
memory usage: 258.9 KB


In [11]:
dataset.shape

(6624, 5)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X = dataset.drop(labels = ['SM (0-5cm)'],axis = 1)
X.shape

(6624, 4)

In [13]:
y = dataset['SM (0-5cm)']
X = sc.fit_transform(X)
print(X)

[[-0.18578096 -0.56634579 -0.52407889 -0.35620143]
 [-0.21260266 -0.64497577 -0.60657612 -0.43442445]
 [-0.23271893 -0.71547162 -0.67685153 -0.50924646]
 ...
 [ 0.08914145  0.30942955  0.41394513  0.57227177]
 [ 0.08243603  0.27147025  0.36505788  0.51785576]
 [ 0.08243603  0.22537681  0.31617064  0.46343975]]


In [14]:
print(y)

0       16.92
1       16.82
2       16.49
3       16.75
4       16.76
        ...  
6619     9.44
6620     9.44
6621     9.44
6622     9.19
6623     9.19
Name: SM (0-5cm), Length: 6624, dtype: float64


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [16]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [17]:
accuracy = regressor.score(X_test,y_test)
print(accuracy*100,'%')

85.12610478832107 %


In [19]:
y_pred = regressor.predict(X_test)
print(y_pred)

[16.467 11.651 23.577 ... 23.6   20.578 23.902]


In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8512610478832108

In [21]:
from sklearn.svm import SVR
regressor_svm = SVR(kernel = 'rbf')
regressor_svm.fit(X, y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [22]:
accuracy = regressor_svm.score(X_test,y_test)
print(accuracy*100,'%')

-6.432505150021339 %
